### ISSUE TITLE
Download problem of N-UCLA dataset

### ISSUE THREAD

**Issue by liujiaheng** [3huo/3DV-Action#4]
Hi, I tried to download the N-UCLA data from http://wangjiangb.github.io/my_data.html. But I cannot decompress the downloaded archive files successfully. The error is that the files are corrupted.
Have you met this problem?

Thanks.
Looking forward to your reply.

**Comment by liujiaheng** [comment]
Besides, could you check the camera intrinsics of UWA? I tried to convert the depth map of UWA dataset to point cloud. I found that the generated point cloud may exist some errors.

Thanks.

**Comment by 3huo** [comment]
Due to the camera intrinsics of uwa and N-ucla are not known, the concerting to point cloud may shows not very strict. And I thought the intrinsics are not very important for 3DV, so I didn't spend much time on that. If you don't mind, It would great for ajusting them to better.

**Comment by 3huo** [comment]
I download this dataset a long time ago, so I have no idea for the download program(>﹏<)

**Comment by liujiaheng** [comment]
Thanks for your reply. I will try to download the N-UCLA dataset.

**Comment by liujiaheng** [comment]
BTW, could you provide the train and test code of UWA dataset?

**Comment by liujiaheng** [comment]
Because I find that training process of UWA is easy to overfit. The test accuracy is low. I just want to know some tricks or augmentation strategies to train the UWA dataset.
